Build blog code with nix
I still need to include the test data in the artifact.

error: builder for '/nix/store/81yc6m0dm49xp9xarpg8v09vpyhmf0hs-blog-0.1.0.drv'
failed with exit code 101;
       last 10 log lines:
       > thread 'tests::test_read_post_0' panicked at 'Could not read post: IO(O
s { code: 2, kind: NotFound, message: "No such file or directory" })', src/lib.r
s:409:36
       > note: run with `RUST_BACKTRACE=1` environment variable to display a bac
ktrace
       >
       >
       > failures:
       >     tests::test_read_post_0
       >
       > test result: FAILED. 7 passed; 1 failed; 2 ignored; 0 measured; 0 filte
red out; finished in 0.00s
       >
       > error: test failed, to rerun pass `--lib`
       For full logs, run 'nix log /nix/store/81yc6m0dm49xp9xarpg8v09vpyhmf0hs-b
log-0.1.0.drv'.